set(CMAKE_IMPORT_FILE_VERSION 1)

set(
  MCTCLIB_INCLUDEDIRS
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@"
  "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_INCLUDEDIR@/@module-dir@"
)
find_library(
  MCTCLIB_LIBRARIES
  "@PROJECT_NAME@"
  PATHS "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LIBDIR@"
  NO_DEFAULT_PATH
)
set(
  MCTCLIB_DEPENDENCIES
  "$<$<BOOL:${MCTCLIB_USE_JONQUIL}>:jonquil::jonquil>"
  "$<$<BOOL:${MCTCLIB_USE_TOMLF}>:toml-f::toml-f>"
  "$<$<BOOL:${MCTCLIB_WITH_OpenMP}>:OpenMP::OpenMP_Fortran>"
)

add_library(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE IMPORTED)
add_library(@PROJECT_NAME@::@PROJECT_NAME@ ALIAS @PROJECT_NAME@::@PROJECT_NAME@-lib)
target_link_libraries(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${MCTCLIB_LIBRARIES} ${MCTCLIB_DEPENDENCIES})
target_include_directories(@PROJECT_NAME@::@PROJECT_NAME@-lib INTERFACE ${MCTCLIB_INCLUDEDIRS})
